/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <miso_aliases.h>
#include <miso.h>
#include <Clock_1.h>
#include <ss_aliases.h>
#include <ss.h>
#include <sclk_aliases.h>
#include <sclk.h>
#include <mosi_aliases.h>
#include <mosi.h>
#include <cs_aliases.h>
#include <cs.h>
#include <dc_aliases.h>
#include <dc.h>
#include <rt_cs_aliases.h>
#include <rt_cs.h>
#include <TFTSHIELD_1.h>
#include <TFTSHIELD_1_SPIM_1.h>
#include <TFTSHIELD_1_SPIM_1_PVT.h>
#include <TFTSHIELD_1_CR_1.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

