# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Brian\Dropbox\RPiSoC\Projects\tft_test.Bundle01_Rev_b - touch\tft_test.cydsn\tft_test.cyprj
# Date: Mon, 30 Jun 2014 20:02:03 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]


# Component constraints for C:\Users\Brian\Dropbox\RPiSoC\Projects\tft_test.Bundle01_Rev_b - touch\tft_test.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Brian\Dropbox\RPiSoC\Projects\tft_test.Bundle01_Rev_b - touch\tft_test.cydsn\tft_test.cyprj
# Date: Mon, 30 Jun 2014 20:01:51 GMT
